import test from 'node:test';import assert from 'node:assert/strict';
import {sendMail,supportMessage,makeLimiter,TEST_SENDER,type MailMessage} from '../lib/mail.ts';
import type {Member} from '../lib/domain.ts';
const msg:MailMessage={to:'support@example.test',subject:'Hello',text:'Body',replyTo:'person@example.test'};
const member:Member={id:'m1',name:'Casey Jones',email:'casey@example.test',role:'Analyst',teams:[],contractor:''};
type Call={url:string,init:{method:string,headers:Record<string,string>,body:string}};
function fakeFetch(status:number,body='',fail?:Error){const calls:Call[]=[];const f=async(url:string,init:{method:string,headers:Record<string,string>,body:string})=>{calls.push({url,init});if(fail)throw fail;return {ok:status>=200&&status<300,status,async text(){return body}}};return {f,calls}}

test('nothing is sent and nothing is called when no API key is set',async()=>{const {f,calls}=fakeFetch(200);assert.deepEqual(await sendMail(msg,{},f),{ok:false,reason:'not-configured'});assert.deepEqual(await sendMail(msg,{RESEND_API_KEY:'   '},f),{ok:false,reason:'not-configured'});assert.equal(calls.length,0)});
test('a configured send posts to Resend with the key, the test sender and a reply-to',async()=>{const {f,calls}=fakeFetch(200);const r=await sendMail(msg,{RESEND_API_KEY:'re_test'},f);assert.deepEqual(r,{ok:true});assert.equal(calls.length,1);assert.equal(calls[0].url,'https://api.resend.com/emails');assert.equal(calls[0].init.method,'POST');assert.equal(calls[0].init.headers.Authorization,'Bearer re_test');const sent=JSON.parse(calls[0].init.body);assert.equal(sent.from,TEST_SENDER);assert.deepEqual(sent.to,['support@example.test']);assert.equal(sent.reply_to,'person@example.test');assert.equal(sent.subject,'Hello');assert.equal(sent.text,'Body')});
test('MAIL_FROM overrides the sender and reply-to is optional',async()=>{const {f,calls}=fakeFetch(200);await sendMail({to:'a@example.test',subject:'s',text:'t'},{RESEND_API_KEY:'k',MAIL_FROM:'PaveLedger <notices@example.test>'},f);const sent=JSON.parse(calls[0].init.body);assert.equal(sent.from,'PaveLedger <notices@example.test>');assert.equal('reply_to' in sent,false)});
test('provider rejections and outages are reported without throwing',async()=>{const k={RESEND_API_KEY:'k'};assert.equal((await sendMail(msg,k,fakeFetch(403,'only your own email').f) as {reason:string}).reason,'rejected');assert.equal((await sendMail(msg,k,fakeFetch(422,'bad').f) as {reason:string}).reason,'rejected');assert.equal((await sendMail(msg,k,fakeFetch(500,'oops').f) as {reason:string}).reason,'unavailable');assert.equal((await sendMail(msg,k,fakeFetch(429,'slow down').f) as {reason:string}).reason,'unavailable');const net=await sendMail(msg,k,fakeFetch(200,'',new Error('network down')).f);assert.equal((net as {reason:string}).reason,'unavailable');assert.match((net as {detail:string}).detail,/network down/)});
test('the provider error text is kept short',async()=>{const r=await sendMail(msg,{RESEND_API_KEY:'k'},fakeFetch(500,'x'.repeat(5000)).f);assert.ok((r as {detail:string}).detail.length<=300)});
test('the support message carries the form text and who is signed in',()=>{const m=supportMessage(member,{name:'Casey J',email:'casey.j@example.test',message:'  The map will not load.  '},'support@example.test');assert.equal(m.to,'support@example.test');assert.equal(m.replyTo,'casey.j@example.test');assert.match(m.subject,/^PaveLedger support: Casey J$/);assert.match(m.text,/^The map will not load\./);assert.match(m.text,/From: Casey J <casey\.j@example\.test>/);assert.match(m.text,/Signed in as: Casey Jones \(Analyst, casey@example\.test\)/)});
test('line breaks cannot be smuggled into the subject or reply-to',()=>{const m=supportMessage(member,{name:'Eve\r\nBcc: boss@example.test',email:'eve@example.test\nBcc: x@example.test',message:'hello there'},'support@example.test');assert.equal(/[\r\n]/.test(m.subject),false);assert.equal(/[\r\n]/.test(m.replyTo||''),false);assert.ok(m.subject.length<=100)});
test('the limiter allows a few messages per window and then blocks',()=>{const ok=makeLimiter(3,600_000);assert.equal(ok('u1',0),true);assert.equal(ok('u1',1000),true);assert.equal(ok('u1',2000),true);assert.equal(ok('u1',3000),false);assert.equal(ok('u2',3000),true)});
test('the limiter lets messages through again after the window',()=>{const ok=makeLimiter(1,1000);assert.equal(ok('u',0),true);assert.equal(ok('u',500),false);assert.equal(ok('u',1001),true)});
