import test from 'node:test';import assert from 'node:assert/strict';
import {seed,normalizeState,type Member,type State,type Ticket} from '../lib/domain.ts';
import {applyAction} from '../lib/actions.ts';
import {buildNotice,queueNotice,runOutbox,retryFailed,MAX_OUTBOX} from '../lib/outbox.ts';
import type {MailMessage,MailResult} from '../lib/mail.ts';
const now='2026-09-25T19:00:00.000Z',owner='d226cfb5-73e3-41f2-8a21-d7721b3a40de';
const note='Reviewed evidence and recorded the required next action.';
const fixture=()=>{const s=normalizeState(seed(owner,'owner@example.test'));for(const t of s.tickets)t.created='2026-09-24T19:00:00.000Z';return {s,admin:s.members[0],lead:s.members.find(x=>x.role==='Team lead')!,analyst:s.members.find(x=>x.id==='demo-analyst')!,contractor:s.members.find(x=>x.role==='Contractor')!,auditor:s.members.find(x=>x.role==='Auditor')!,t:s.tickets[0]}};
const act=(s:State,who:Member,body:Record<string,unknown>)=>applyAction(s,who,who,body,now,owner);
const prepare=(s:State,who:Member,t:Ticket)=>{t.status='Confirmed';act(s,who,{action:'transition',id:t.id,status:'Notice prepared',note,contract:s.contracts[0].id,scopeConfirmed:true})};
const ok:MailResult={ok:true};
function harness(send?:(m:MailMessage)=>Promise<MailResult>,save?:()=>Promise<boolean>){
 const sent:MailMessage[]=[];const counts={saves:0};
 const io={appUrl:'https://app.example.test',save:save||(async()=>{counts.saves++;return true}),send:send||(async(m:MailMessage)=>{sent.push(m);return ok})};
 return {sent,counts,io};
}

// Models the database: a save stores a copy, and a later request loads that copy.
function database(s:State,failFrom=0){
 const db={persisted:structuredClone(s),saves:0};
 const save=async()=>{db.saves++;if(failFrom&&db.saves>=failFrom)return false;db.persisted=structuredClone(s);return true};
 return {db,save};
}
test('the notice contains only contractor-facing facts',()=>{const {s,t}=fixture();t.note='INTERNAL: analyst suspects the road crew';t.history.push({at:now,actor:'x',action:'y',note:'INTERNAL history',visibility:'internal'});const n=buildNotice(t,s.contracts[0]);assert.match(n.text,new RegExp(t.id));assert.match(n.text,/King Street East/);assert.match(n.text,/CT-DEMO-104/);assert.match(n.text,/google\.com\/maps\?q=/);assert.equal(/INTERNAL/.test(n.text),false);assert.equal(/DRAFT/.test(n.text),false);assert.equal(/[\r\n]/.test(n.subject),false)});
test('nothing is queued when automatic notices are off',()=>{const {s,admin,t}=fixture();prepare(s,admin,t);assert.equal((s.outbox||[]).length,0)});
test('preparing a notice queues one email when automatic notices are on',()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);assert.equal(s.outbox?.length,1);const i=s.outbox![0];assert.equal(i.status,'queued');assert.equal(i.to,s.contracts[0].email);assert.equal(i.replyTo,'owner@example.test');assert.equal(i.ticket,t.id);assert.ok(t.history.some(h=>h.action==='Notice email queued'))});
test('a contract without a valid contact email is skipped with a note',()=>{const {s,admin,t}=fixture();s.contracts[0].email='not-an-email';act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);assert.equal((s.outbox||[]).length,0);assert.ok(t.history.some(h=>h.action==='Notice email not queued'));assert.equal(t.status,'Notice prepared')});
test('a second notice is not queued while one is waiting',()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);assert.equal(queueNotice(s,t,s.contracts[0],admin,now),null);assert.equal(s.outbox?.length,1)});
test('only an administrator can switch automatic notices or retry failures',()=>{const {s,lead,analyst,admin}=fixture();assert.throws(()=>act(s,lead,{action:'autoNotice',enabled:true}));assert.throws(()=>act(s,analyst,{action:'outboxRetry'}));assert.throws(()=>act(s,admin,{action:'autoNotice',enabled:'yes'}));assert.equal(s.autoNotice,undefined);act(s,admin,{action:'autoNotice',enabled:true});assert.equal(s.autoNotice,true);assert.match(s.events[0].action,/enabled/)});
test('staff can email an already prepared notice on request',()=>{const {s,admin,t}=fixture();prepare(s,admin,t);act(s,admin,{action:'noticeSend',id:t.id});assert.equal(s.outbox?.length,1);assert.equal(s.outbox![0].status,'queued')});
test('a notice cannot be emailed before it has been prepared',()=>{const {s,admin,t}=fixture();t.status='Investigating';assert.throws(()=>act(s,admin,{action:'noticeSend',id:t.id}),/Prepare the notice first/);assert.equal((s.outbox||[]).length,0)});
test('roles without access cannot email a notice',()=>{const {s,admin,t,contractor,auditor,analyst}=fixture();prepare(s,admin,t);assert.throws(()=>act(s,contractor,{action:'noticeSend',id:t.id}));assert.throws(()=>act(s,auditor,{action:'noticeSend',id:t.id}));t.analyst='';assert.throws(()=>act(s,analyst,{action:'noticeSend',id:t.id}),/not found/i);assert.equal((s.outbox||[]).length,0)});
test('a notice is sent once, recorded on the case, and not sent again',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const h=harness();const r=await runOutbox(s,now,h.io);assert.deepEqual(r,{sent:1,failed:0});assert.equal(h.sent.length,1);assert.equal(h.sent[0].to,s.contracts[0].email);assert.equal(h.sent[0].replyTo,'owner@example.test');assert.match(h.sent[0].text,/Open PaveLedger: https:\/\/app\.example\.test/);assert.equal(s.outbox![0].status,'sent');assert.equal(t.noticeEmailedAt,now);assert.ok(t.history.some(x=>x.action==='Notice emailed'));assert.match(s.events[0].action,/Notice emailed/);assert.equal(h.counts.saves,2);const again=await runOutbox(s,now,h.io);assert.deepEqual(again,{sent:0,failed:0});assert.equal(h.sent.length,1)});
test('an item is claimed and saved before any email leaves',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const states:string[]=[];const h=harness(async()=>{states.push(s.outbox![0].status);return ok});await runOutbox(s,now,h.io);assert.deepEqual(states,['sending'])});
test('nothing is sent when the claim cannot be saved',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const h=harness(undefined,async()=>false);const r=await runOutbox(s,now,h.io);assert.deepEqual(r,{sent:0,failed:0});assert.equal(h.sent.length,0)});
test('if the final save fails the stored item stays claimed and is never resent',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const {db,save}=database(s,2);const h=harness(undefined,save);await runOutbox(s,now,h.io);assert.equal(h.sent.length,1);assert.equal(db.persisted.outbox![0].status,'sending');const next=structuredClone(db.persisted);const h2=harness();const later=await runOutbox(next,'2026-09-25T19:10:00.000Z',h2.io);assert.deepEqual(later,{sent:0,failed:0});assert.equal(h2.sent.length,0);assert.equal(next.outbox![0].status,'sending')});
test('a claimed item with no recorded outcome is marked unknown after 30 minutes',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const {db,save}=database(s,2);await runOutbox(s,now,harness(undefined,save).io);const next=structuredClone(db.persisted);const h2=harness();await runOutbox(next,'2026-09-25T19:31:00.000Z',h2.io);assert.equal(h2.sent.length,0);assert.equal(next.outbox![0].status,'failed');assert.match(next.outbox![0].lastError||'',/status unknown/);assert.equal(h2.counts.saves,1)});
test('a rejected email fails at once and can be retried by an administrator',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const h=harness(async()=>({ok:false,reason:'rejected',detail:'domain not verified'}));const r=await runOutbox(s,now,h.io);assert.deepEqual(r,{sent:0,failed:1});assert.equal(s.outbox![0].status,'failed');assert.match(s.outbox![0].lastError||'',/rejected/);assert.ok(t.history.some(x=>x.action==='Notice email failed'));act(s,admin,{action:'outboxRetry'});assert.equal(s.outbox![0].status,'queued');assert.equal(s.outbox![0].attempts,0);const good=harness();await runOutbox(s,now,good.io);assert.equal(s.outbox![0].status,'sent')});
test('temporary outages are retried and give up after three attempts',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const h=harness(async()=>({ok:false,reason:'unavailable',detail:'timeout'}));await runOutbox(s,now,h.io);assert.equal(s.outbox![0].status,'queued');assert.equal(s.outbox![0].attempts,1);await runOutbox(s,now,h.io);assert.equal(s.outbox![0].status,'queued');const last=await runOutbox(s,now,h.io);assert.deepEqual(last,{sent:0,failed:1});assert.equal(s.outbox![0].status,'failed');assert.equal(s.outbox![0].attempts,3)});
test('when email is not configured the item waits without using an attempt',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const h=harness(async()=>({ok:false,reason:'not-configured'}));await runOutbox(s,now,h.io);assert.equal(s.outbox![0].status,'queued');assert.equal(s.outbox![0].attempts,0)});
test('a send that throws is treated as an outage',async()=>{const {s,admin,t}=fixture();act(s,admin,{action:'autoNotice',enabled:true});prepare(s,admin,t);const h=harness(async()=>{throw new Error('boom')});await runOutbox(s,now,h.io);assert.equal(s.outbox![0].status,'queued');assert.match(s.outbox![0].lastError||'',/boom/)});
test('at most the batch size is sent per run, oldest first',async()=>{const {s,admin}=fixture();act(s,admin,{action:'autoNotice',enabled:true});const ids:string[]=[];for(const t of s.tickets.slice(0,4)){t.road='King Street East';prepare(s,admin,t);ids.push(t.id)}const h=harness();await runOutbox(s,now,{...h.io,max:2});assert.equal(h.sent.length,2);assert.match(h.sent[0].subject,new RegExp(ids[0]));assert.match(h.sent[1].subject,new RegExp(ids[1]));assert.equal(s.outbox!.filter(i=>i.status==='queued').length,2)});
test('the outbox is capped and old sent items are dropped first',()=>{const {s,admin}=fixture();s.outbox=Array.from({length:MAX_OUTBOX},(_,k)=>({id:'o'+k,to:'a@example.test',subject:'s',text:'t',ticket:'T'+k,contract:'c',created:now,attempts:1,status:(k<MAX_OUTBOX-1?'sent':'failed') as 'sent'|'failed'}));const t=s.tickets[1];queueNotice(s,t,s.contracts[0],admin,now);assert.equal(s.outbox.length,MAX_OUTBOX);assert.equal(s.outbox[0].status,'queued');assert.ok(s.outbox.some(i=>i.status==='failed'))});
test('retrying with nothing failed changes nothing',()=>{const {s}=fixture();assert.equal(retryFailed(s),0)});
import {mailReady} from '../lib/mail.ts';
test('contractor emails need both an API key and a sender address',()=>{assert.equal(mailReady({}),false);assert.equal(mailReady({RESEND_API_KEY:'k'}),false);assert.equal(mailReady({MAIL_FROM:'PaveLedger <n@example.test>'}),false);assert.equal(mailReady({RESEND_API_KEY:'k',MAIL_FROM:' '}),false);assert.equal(mailReady({RESEND_API_KEY:'k',MAIL_FROM:'PaveLedger <n@example.test>'}),true)});
