import test from 'node:test';import assert from 'node:assert/strict';
import {seed,normalizeState,canSee,permitted,roles,type Member,type State,type Evidence,type Ticket} from '../lib/domain.ts';
import {applyAction} from '../lib/actions.ts';
const now='2026-10-09T12:00:00.000Z',owner='d226cfb5-73e3-41f2-8a21-d7721b3a40de';
const note='Reviewed evidence and recorded the required next action.';
const fixture=()=>{const s=normalizeState(seed(owner,'owner@example.test'));for(const t of s.tickets)t.created='2026-09-24T19:00:00.000Z';return {s,admin:s.members[0],lead:s.members.find(x=>x.id==='demo-lead')!,analyst:s.members.find(x=>x.id==='demo-analyst')!,auditor:s.members.find(x=>x.id==='demo-reviewer')!,director:undefined as Member|undefined,t:s.tickets[0]}};
const act=(s:State,who:Member,body:Record<string,unknown>)=>applyAction(s,who,who,body,now,owner);
let n=0;
const person=(role:string,over:Record<string,unknown>={})=>({action:'member',name:'Test Person',email:`rm${++n}@example.test`,role,teams:['Central roads'],contractor:'',active:true,authUserId:crypto.randomUUID(),...over});
const verification=(t:Ticket):Evidence=>({id:'evidence-a',name:'repeat.png',mime:'image/png',bytes:400,sha256:'testhash',purpose:'verification',capturedAt:'2026-09-25T18:55:00.000Z',uploadedAt:now,uploadedBy:'someone',lat:t.lat,lng:t.lng,accuracy:3,lane:t.lane!,quality:'clear'});

test('Team lead and Reviewer are no longer roles',()=>{assert.equal((roles as readonly string[]).includes('Team lead'),false);assert.equal((roles as readonly string[]).includes('Reviewer'),false);const {s,admin}=fixture();assert.throws(()=>act(s,admin,person('Team lead')),/Unknown role/);assert.throws(()=>act(s,admin,person('Reviewer')),/Unknown role/)});
test('they cannot be the base of a custom role either',()=>{const {s,admin}=fixture();for(const base of ['Team lead','Reviewer'])assert.throws(()=>act(s,admin,{action:'customRoleSave',name:'Old style',base,visibility:'base',caps:['comment']}));assert.equal(s.customRoles,undefined)});
test('the demo team lead is now a head analyst and the demo reviewer an auditor',()=>{const {lead,auditor}=fixture();assert.equal(lead.role,'Head Analyst');assert.equal(auditor.role,'Auditor')});

// ---- Head Analyst now has everything a Team lead had
const base={action:'create',road:'King Street East',title:'Pothole in travel lane',lat:43.3605,lng:-80.314,accuracy:5,lane:'Lane 1',note:'Deep pothole near the crosswalk, about 40 cm wide.'};
test('a head analyst can create tickets for their own team only',()=>{const {s,lead}=fixture();act(s,lead,base);assert.equal(s.tickets[0].team,'Central roads');assert.throws(()=>act(s,lead,{...base,team:'East roads'}),/own teams/)});
test('a head analyst can assign analysts in their own team only',()=>{const {s,lead,analyst,t}=fixture();act(s,lead,{action:'assign',id:t.id,team:'Central roads',analyst:analyst.id});assert.equal(t.analyst,analyst.id);assert.throws(()=>act(s,lead,{action:'assign',id:t.id,team:'East roads',analyst:''}),/accessible team/)});
test('a head analyst only sees the tickets of their own teams',()=>{const {s,lead}=fixture();for(const t of s.tickets)assert.equal(canSee(t,lead),lead.teams.includes(t.team))});
test('a head analyst can archive and unarchive closed tickets',()=>{const {s,lead,t}=fixture();t.status='Verified closed';act(s,lead,{action:'archive',id:t.id});assert.equal(t.archived,true);act(s,lead,{action:'unarchive',id:t.id});assert.equal(t.archived,false)});
test('a head analyst can add and edit members and edit locations',()=>{const {s,lead,t}=fixture();const before=s.members.length;act(s,lead,person('Analyst'));assert.equal(s.members.length,before+1);act(s,lead,{action:'ticketLocation',id:t.id,address:'55 Water Street'});assert.equal(t.address,'55 Water Street')});
test('a head analyst still cannot grant Admin or manage vehicle accounts',()=>{const {s,lead}=fixture();assert.throws(()=>act(s,lead,person('Admin')),/administrator/);assert.throws(()=>act(s,lead,person('Vehicle',{vehicleTag:'Truck-1',teams:[]})),/administrator/)});

// ---- Auditor now has everything a Reviewer had
test('an auditor can reopen a closed ticket and put a ticket on hold and resume it',()=>{const {s,auditor,t}=fixture();t.status='Verified closed';act(s,auditor,{action:'transition',id:t.id,status:'Reopened',note});assert.equal(t.status,'Reopened');t.status='Investigating';act(s,auditor,{action:'transition',id:t.id,status:'On hold',note});assert.equal(t.status,'On hold');act(s,auditor,{action:'transition',id:t.id,status:'Investigating',note});assert.equal(t.status,'Investigating')});
test('an auditor can close a verified repair when they did not claim it',()=>{const {s,auditor,t}=fixture();t.status='Awaiting verification';t.completedAt='2026-09-25T18:00:00.000Z';t.completedBy='other';t.evidence=[verification(t)];act(s,auditor,{action:'transition',id:t.id,status:'Verified closed',verification:'clear-pass',evidenceId:'evidence-a',note});assert.equal(t.status,'Verified closed');assert.equal(t.closedBy,auditor.id)});
test('an auditor cannot close without evidence and cannot self-verify',()=>{const {s,auditor,admin,t}=fixture();t.status='Awaiting verification';assert.throws(()=>act(s,auditor,{action:'transition',id:t.id,status:'Verified closed',verification:'clear-pass',note}));t.completedAt='2026-09-25T18:00:00.000Z';t.completedBy=auditor.id;t.evidence=[verification(t)];assert.throws(()=>act(s,auditor,{action:'transition',id:t.id,status:'Verified closed',verification:'clear-pass',evidenceId:'evidence-a',note}));assert.equal(admin.role,'Admin')});
test('an auditor cannot make routine stage changes',()=>{const {auditor,t}=fixture();for(const next of ['Team assigned','Investigating','Confirmed','Notice prepared','Repair in progress'])assert.equal(permitted(auditor,t,next),false,next)});
test('an auditor sees every ticket and can comment but not create, assign or archive',()=>{const {s,auditor,t}=fixture();for(const x of s.tickets)assert.equal(canSee(x,auditor),true);act(s,auditor,{action:'note',id:t.id,note,visibility:'internal'});assert.throws(()=>act(s,auditor,base));assert.throws(()=>act(s,auditor,{action:'assign',id:t.id,team:'Central roads',analyst:''}));t.status='Verified closed';assert.throws(()=>act(s,auditor,{action:'archive',id:t.id}))});
test('a director still cannot move tickets',()=>{const {s,admin,t}=fixture();act(s,admin,person('Director',{teams:[]}));const dir=s.members.at(-1)!;t.status='Verified closed';assert.equal(permitted(dir,t,'Reopened'),false)});

// ---- existing data is migrated automatically
test('legacy Team lead and Reviewer members, permissions, chains and tickets are migrated',()=>{
 const s=normalizeState(seed(owner,'owner@example.test'));
 const lead=s.members.find(x=>x.id==='demo-lead')!,rev=s.members.find(x=>x.id==='demo-reviewer')!;(lead as any).role='Team lead';(rev as any).role='Reviewer';
 s.rolePermissions={'Team lead':['create','assign','archive'],'Head Analyst':['comment','escalate'],Reviewer:['comment'],Auditor:[],Analyst:['create']};
 s.customRoles=[{name:'Old lead',base:'Team lead' as any,visibility:'team',caps:['assign']},{name:'Old reviewer',base:'Reviewer' as any,visibility:'base',caps:[]}];
 s.escalationChain=['Head Analyst','Team lead','Director'];s.tickets[0].escalatedTo='Team lead';s.tickets[1].escalatedTo='Director';
 normalizeState(s);
 assert.equal(lead.role,'Head Analyst');assert.equal(rev.role,'Auditor');
 assert.deepEqual([...(s.rolePermissions!['Head Analyst'])].sort(),['archive','assign','comment','create','escalate']);assert.deepEqual(s.rolePermissions!['Auditor'],['comment']);assert.equal('Team lead' in s.rolePermissions!,false);assert.equal('Reviewer' in s.rolePermissions!,false);assert.deepEqual(s.rolePermissions!.Analyst,['create']);
 assert.deepEqual(s.customRoles!.map(r=>r.base),['Head Analyst','Auditor']);
 assert.deepEqual(s.escalationChain,['Head Analyst','Director']);assert.equal(s.tickets[0].escalatedTo,'Head Analyst');assert.equal(s.tickets[1].escalatedTo,'Director');
 const snapshot=JSON.stringify(s);normalizeState(s);assert.equal(JSON.stringify(s),snapshot)});
test('a chain that collapses to one role is reset to the default',()=>{const s=normalizeState(seed(owner,'owner@example.test'));s.escalationChain=['Team lead','Head Analyst'];normalizeState(s);assert.equal(s.escalationChain,undefined);s.escalationChain=['Team lead','Director'];normalizeState(s);assert.deepEqual(s.escalationChain,['Head Analyst','Director'])});
test('migrated members of a custom role keep it and the visibility',()=>{const s=normalizeState(seed(owner,'owner@example.test'));const m=s.members.find(x=>x.id==='demo-lead')!;(m as any).role='Team lead';m.customRole='Old lead';m.visibility='team';s.customRoles=[{name:'Old lead',base:'Team lead' as any,visibility:'team',caps:['assign']}];normalizeState(s);assert.equal(m.role,'Head Analyst');assert.equal(m.customRole,'Old lead');assert.equal(m.visibility,'team')});
test('current data is not touched by the migration',()=>{const s=normalizeState(seed(owner,'owner@example.test'));const before=JSON.stringify(s);normalizeState(s);assert.equal(JSON.stringify(s),before)});

// ---- an analyst can belong to several teams
const analystUpdate=(a:Member,teams:string[],over:Record<string,unknown>={})=>({action:'memberUpdate',memberId:a.id,name:a.name,email:a.email,role:'Analyst',teams,contractor:'',active:true,authUserId:a.authUserId,...over});
const prep=()=>{const f=fixture();f.analyst.authUserId=crypto.randomUUID();return f};
test('an analyst with open tickets can be added to another team',()=>{const {s,admin,analyst}=prep();assert.ok(s.tickets.some(t=>t.analyst===analyst.id&&t.status!=='Verified closed'));act(s,admin,analystUpdate(analyst,['Central roads','East roads']));assert.deepEqual([...analyst.teams].sort(),['Central roads','East roads'])});
test('a head analyst can add an analyst to a second team too',()=>{const {s,lead,analyst}=prep();act(s,lead,analystUpdate(analyst,['Central roads','East roads']));assert.equal(analyst.teams.length,2)});
test('the analyst can then be given tickets from either team and work them with any contract',()=>{const {s,admin,analyst}=prep();act(s,admin,analystUpdate(analyst,['Central roads','East roads']));act(s,admin,{...base,team:'East roads'});const t=s.tickets[0];assert.equal(t.team,'East roads');act(s,admin,{action:'assign',id:t.id,team:'East roads',analyst:analyst.id});assert.equal(t.analyst,analyst.id);t.status='Confirmed';assert.equal(canSee(t,analyst),true);act(s,analyst,{action:'transition',id:t.id,status:'Notice prepared',note,contract:s.contracts[0].id,scopeConfirmed:true});assert.equal(t.status,'Notice prepared');assert.equal(t.contractId,s.contracts[0].id)});
test('removing a team where the analyst still has open tickets is refused',()=>{const {s,admin,analyst}=prep();const open=s.tickets.find(t=>t.analyst===analyst.id&&t.status!=='Verified closed')!;act(s,admin,analystUpdate(analyst,['Central roads','East roads']));assert.throws(()=>act(s,admin,analystUpdate(analyst,['East roads'])),/Reassign.*Central roads/);assert.ok(analyst.teams.includes(open.team))});
test('removing a team where they have no open tickets is allowed',()=>{const {s,admin,analyst}=prep();act(s,admin,analystUpdate(analyst,['Central roads','East roads']));act(s,admin,analystUpdate(analyst,['Central roads']));assert.deepEqual(analyst.teams,['Central roads'])});
test('suspending or changing the role of an analyst with open tickets is still refused',()=>{const {s,admin,analyst}=prep();assert.throws(()=>act(s,admin,analystUpdate(analyst,['Central roads'],{active:false})),/Reassign/);assert.throws(()=>act(s,admin,analystUpdate(analyst,['Central roads'],{role:'Head Analyst'})),/Reassign/);assert.equal(analyst.active!==false,true)});
test('no more than three teams per person',()=>{const {s,admin,analyst}=prep();s.teams.push('South roads','North roads');assert.throws(()=>act(s,admin,analystUpdate(analyst,['Central roads','East roads','South roads','North roads'])));act(s,admin,analystUpdate(analyst,['Central roads','East roads','South roads']));assert.equal(analyst.teams.length,3)});
