import test from 'node:test';import assert from 'node:assert/strict';
import {seed,normalizeState,type Member,type State} from '../lib/domain.ts';
import {applyAction} from '../lib/actions.ts';
const now='2026-10-09T12:00:00.000Z',owner='d226cfb5-73e3-41f2-8a21-d7721b3a40de';
const fixture=()=>{const s=normalizeState(seed(owner,'owner@example.test'));return {s,admin:s.members[0],lead:s.members.find(x=>x.role==='Team lead')!,analyst:s.members.find(x=>x.id==='demo-analyst')!,other:s.members.find(x=>x.id==='demo-analyst-2')!,contractor:s.members.find(x=>x.role==='Contractor')!,auditor:s.members.find(x=>x.role==='Auditor')!}};
const act=(s:State,who:Member,body:Record<string,unknown>)=>applyAction(s,who,who,body,now,owner);
const base={action:'create',road:'King Street East',title:'Pothole in travel lane',lat:43.3605,lng:-80.314,accuracy:5,lane:'Lane 1',note:'Deep pothole near the crosswalk, about 40 cm wide.'};
const create=(s:State,who:Member,over:Record<string,unknown>={})=>{act(s,who,{...base,...over});return s.tickets[0]};

test('a new ticket keeps its address, observation time, source and team',()=>{const {s,admin}=fixture();const t=create(s,admin,{address:'123 King Street East, Waterloo, ON',observedAt:'2026-10-09T09:30:00.000Z',source:'Resident report',team:'East roads',severity:'Urgent'});assert.equal(t.address,'123 King Street East, Waterloo, ON');assert.equal(t.observedAt,'2026-10-09T09:30:00.000Z');assert.equal(t.source,'Resident report');assert.equal(t.team,'East roads');assert.equal(t.severity,'Urgent');assert.equal(t.lat,43.3605)});
test('the old form still works and defaults are unchanged',()=>{const {s,lead}=fixture();const t=create(s,lead);assert.equal(t.source,'Manual report');assert.equal(t.team,lead.teams[0]);assert.equal(t.address,undefined);assert.equal(t.observedAt,undefined);assert.equal(t.status,'Detected')});
test('a team lead can only create tickets for their own team',()=>{const {s,lead}=fixture();assert.ok(!lead.teams.includes('East roads'));assert.throws(()=>create(s,lead,{team:'East roads'}),/own teams/);assert.throws(()=>create(s,lead,{team:'No such team'}));const t=create(s,lead,{team:lead.teams[0]});assert.equal(t.team,lead.teams[0])});
test('the observation time cannot be in the future or over a year old',()=>{const {s,admin}=fixture();const before=s.tickets.length;assert.throws(()=>create(s,admin,{observedAt:'2026-10-09T13:00:00.000Z'}),/future/);assert.throws(()=>create(s,admin,{observedAt:'2025-10-01T00:00:00.000Z'}),/year old/);assert.throws(()=>create(s,admin,{observedAt:'yesterday'}));assert.equal(s.tickets.length,before);create(s,admin,{observedAt:'2026-10-09T12:03:00.000Z'});assert.equal(s.tickets.length,before+1)});
test('the source must be one of the listed choices',()=>{const {s,admin}=fixture();assert.throws(()=>create(s,admin,{source:'Anonymous tip line'}));for(const src of ['Staff report','Resident report','Volunteer report','Field inspection','Manual report','Other']){assert.equal(create(s,admin,{source:src}).source,src)}});
test('address length and note length are still checked',()=>{const {s,admin}=fixture();assert.throws(()=>create(s,admin,{address:'x'.repeat(301)}));assert.throws(()=>create(s,admin,{note:'too short'}));assert.throws(()=>create(s,admin,{lat:91}));assert.throws(()=>create(s,admin,{lng:-181}))});
test('roles that cannot create tickets still cannot',()=>{const {s,contractor,auditor}=fixture();assert.throws(()=>create(s,contractor));assert.throws(()=>create(s,auditor))});

const loc=(s:State,who:Member,id:string,over:Record<string,unknown>={})=>act(s,who,{action:'ticketLocation',id,...over});
test('an administrator can change the address and the coordinates',()=>{const {s,admin}=fixture();const t=s.tickets[2];const n=t.history.length;loc(s,admin,t.id,{address:'55 Water Street, Cambridge',lat:43.3612,lng:-80.3101,accuracy:3.5});assert.equal(t.address,'55 Water Street, Cambridge');assert.equal(t.lat,43.3612);assert.equal(t.lng,-80.3101);assert.equal(t.accuracy,3.5);assert.equal(t.updated,now);assert.equal(t.history.length,n+1);const h=t.history.at(-1)!;assert.equal(h.action,'Location updated');assert.equal(h.visibility,'internal');assert.match(h.note,/address/);assert.match(h.note,/GPS coordinates \(/);assert.match(h.note,/not re-checked/);assert.match(s.events[0].action,/^Location updated /)});
test('the road name and lane can be corrected without touching the contract tag',()=>{const {s,admin}=fixture();const t=s.tickets[2];const tag=t.contractor;loc(s,admin,t.id,{road:'Hespeler Road',lane:'Lane 2'});assert.equal(t.road,'Hespeler Road');assert.equal(t.lane,'Lane 2');assert.equal(t.contractor,tag)});
test('the assigned analyst and the team lead can edit, others cannot',()=>{const {s,lead,analyst,other,contractor,auditor}=fixture();const t=s.tickets[2];assert.equal(t.analyst,analyst.id);loc(s,analyst,t.id,{address:'Edited by analyst'});assert.equal(t.address,'Edited by analyst');loc(s,lead,t.id,{address:'Edited by lead'});assert.equal(t.address,'Edited by lead');assert.throws(()=>loc(s,other,t.id,{address:'nope'}));assert.throws(()=>loc(s,contractor,t.id,{address:'nope'}));assert.throws(()=>loc(s,auditor,t.id,{address:'nope'}));assert.equal(t.address,'Edited by lead')});
test('a closed case must be reopened before its location changes',()=>{const {s,admin}=fixture();const t=s.tickets[2];t.status='Verified closed';assert.throws(()=>loc(s,admin,t.id,{address:'x'}),/Reopen/);t.status='Rejected';assert.throws(()=>loc(s,admin,t.id,{address:'x'}),/Reopen/)});
test('coordinates must come as a pair and stay in range',()=>{const {s,admin}=fixture();const t=s.tickets[2];const lat=t.lat;assert.throws(()=>loc(s,admin,t.id,{lat:43.5}),/both/);assert.throws(()=>loc(s,admin,t.id,{lng:-80.5}),/both/);assert.throws(()=>loc(s,admin,t.id,{lat:95,lng:-80}));assert.throws(()=>loc(s,admin,t.id,{lat:43,lng:-200}));assert.throws(()=>loc(s,admin,t.id,{accuracy:0}));assert.equal(t.lat,lat)});
test('an edit that changes nothing is refused and an unknown case is not found',()=>{const {s,admin}=fixture();const t=s.tickets[2];assert.throws(()=>loc(s,admin,t.id,{lat:t.lat,lng:t.lng,road:t.road}),/Nothing to change/);assert.throws(()=>loc(s,admin,'PL-0000',{address:'x'}),/not found/i)});
test('the address can be cleared',()=>{const {s,admin}=fixture();const t=s.tickets[2];t.address='Old address';loc(s,admin,t.id,{address:''});assert.equal(t.address,'')});
test('someone who can see a case but is not responsible for it cannot edit its location',()=>{const {s,admin}=fixture();const t=s.tickets[2];const reviewer=s.members.find(x=>x.role==='Reviewer')!;assert.ok(reviewer.teams.includes(t.team));assert.throws(()=>loc(s,reviewer,t.id,{address:'x'}),/not permitted/);
act(s,admin,{action:'customRoleSave',name:'Roaming analyst',base:'Analyst',visibility:'all',caps:['comment']});act(s,admin,{action:'member',name:'Roaming Person',email:'roam@example.test',role:'Roaming analyst',teams:['Central roads'],contractor:'',active:true,authUserId:crypto.randomUUID()});const roamer=s.members.at(-1)!;assert.notEqual(t.analyst,roamer.id);assert.throws(()=>loc(s,roamer,t.id,{address:'x'}),/not permitted/);assert.equal(t.address,undefined);
t.analyst=roamer.id;loc(s,roamer,t.id,{address:'Now assigned to them'});assert.equal(t.address,'Now assigned to them')});
