import test from 'node:test';import assert from 'node:assert/strict';
import {seed,normalizeState,type Member,type State} from '../lib/domain.ts';
import {provisionMember,resetMemberPassword,deleteMember,tempPassword,type LoginDeps} from '../lib/users.ts';
const now='2026-10-05T12:00:00.000Z',owner='d226cfb5-73e3-41f2-8a21-d7721b3a40de';
const fixture=()=>{const s=normalizeState(seed(owner,'owner@example.test'));return {s,admin:s.members[0],lead:s.members.find(x=>x.role==='Team lead')!,analyst:s.members.find(x=>x.id==='demo-analyst')!}};
function fakeDeps(over:Partial<LoginDeps>={}){
 const calls={create:[] as {email:string,password:string,mustChange:boolean}[],invite:[] as {email:string,mustChange:boolean}[],setPassword:[] as {id:string,password:string}[],del:[] as string[]};
 const deps:LoginDeps={
  async createLogin(email,password,mustChange){calls.create.push({email,password,mustChange});return crypto.randomUUID()},
  async inviteLogin(email,mustChange){calls.invite.push({email,mustChange});return crypto.randomUUID()},
  async setPassword(id,password){calls.setPassword.push({id,password})},
  async deleteLogin(id){calls.del.push(id)},
  ...over};
 return {deps,calls};
}
const ok=async()=>true,notOk=async()=>false;
const person=(over:Record<string,unknown>={})=>({name:'New Person',email:'New.Person@Example.test',role:'Analyst',teams:['Central roads'],contractor:'',active:true,...over});

test('create makes a login with a temporary password and a linked membership',async()=>{const {s,admin}=fixture();const {deps,calls}=fakeDeps();const r=await provisionMember(s,admin,admin,person(),now,owner,'create',deps,ok);assert.ok(r.password&&r.password.length>=12);assert.equal(calls.create.length,1);assert.equal(calls.create[0].email,'new.person@example.test');assert.equal(calls.create[0].password,r.password);assert.equal(calls.create[0].mustChange,true);const m=s.members.at(-1)!;assert.equal(m.authUserId,r.authUserId);assert.equal(m.role,'Analyst');assert.match(s.events[0].action,/Membership created: New Person/)});
test('an invitation creates the login without returning a password',async()=>{const {s,admin}=fixture();const {deps,calls}=fakeDeps();const r=await provisionMember(s,admin,admin,person(),now,owner,'invite',deps,ok);assert.equal(r.password,undefined);assert.equal(calls.invite.length,1);assert.equal(calls.create.length,0);assert.equal(s.members.at(-1)!.authUserId,r.authUserId)});
test('a vehicle account is not forced to change its password',async()=>{const {s,admin}=fixture();const {deps,calls}=fakeDeps();await provisionMember(s,admin,admin,person({name:'Truck 9',email:'truck9@example.test',role:'Vehicle',teams:[],vehicleTag:'Truck-09'}),now,owner,'create',deps,ok);assert.equal(calls.create[0].mustChange,false);assert.equal(s.members.at(-1)!.role,'Vehicle')});
test('a custom role can be given when creating a user',async()=>{const {s,admin}=fixture();s.customRoles=[{name:'Field inspector',base:'Analyst',visibility:'team',caps:['comment']}];const {deps}=fakeDeps();await provisionMember(s,admin,admin,person({role:'Field inspector'}),now,owner,'create',deps,ok);const m=s.members.at(-1)!;assert.equal(m.role,'Analyst');assert.equal(m.customRole,'Field inspector')});
test('an invalid request never creates a login',async()=>{const {s,admin}=fixture();const {deps,calls}=fakeDeps();await assert.rejects(()=>provisionMember(s,admin,admin,person({role:'Made up role'}),now,owner,'create',deps,ok));await assert.rejects(()=>provisionMember(s,admin,admin,person({email:'owner@example.test'}),now,owner,'create',deps,ok));await assert.rejects(()=>provisionMember(s,admin,admin,person({teams:[]}),now,owner,'create',deps,ok));assert.equal(calls.create.length+calls.invite.length,0);assert.equal(s.members.length,seed(owner,'owner@example.test').members.length)});
test('the login is removed again when the membership cannot be saved',async()=>{const {s,admin}=fixture();const {deps,calls}=fakeDeps();await assert.rejects(()=>provisionMember(s,admin,admin,person(),now,owner,'create',deps,notOk),/simultaneous/);assert.equal(calls.create.length,1);assert.equal(calls.del.length,1)});
test('only an administrator acting as themselves can create users',async()=>{const {s,admin,lead}=fixture();const {deps,calls}=fakeDeps();await assert.rejects(()=>provisionMember(s,lead,lead,person(),now,owner,'create',deps,ok),/administrator/);await assert.rejects(()=>provisionMember(s,lead,admin,person(),now,owner,'create',deps,ok));await assert.rejects(()=>provisionMember(s,admin,lead,person(),now,owner,'create',deps,ok));assert.equal(calls.create.length,0)});
test('temporary passwords are long and different each time',()=>{const a=tempPassword(),b=tempPassword();assert.ok(a.length>=16);assert.notEqual(a,b);assert.match(a,/^[A-Za-z0-9_-]+$/)});

const linked=(s:State,admin:Member)=>{const uid=crypto.randomUUID();const m:Member={id:'u-1',name:'Linked Person',email:'linked@example.test',role:'Auditor',teams:[],contractor:'',authUserId:uid,active:true};s.members.push(m);return m};
test('an administrator can issue a new temporary password for another member',async()=>{const {s,admin}=fixture();const m=linked(s,admin);const {deps,calls}=fakeDeps();const r=await resetMemberPassword(s,admin,admin,m.id,now,owner,deps,ok);assert.ok(r.password.length>=16);assert.deepEqual(calls.setPassword,[{id:m.authUserId!,password:r.password}]);assert.match(s.events[0].action,/Password reset issued for Linked Person/)});
test('password resets are refused for yourself, the owner, demo members and non-admins',async()=>{const {s,admin,lead,analyst}=fixture();const m=linked(s,admin);const {deps,calls}=fakeDeps();await assert.rejects(()=>resetMemberPassword(s,admin,admin,admin.id,now,owner,deps,ok));await assert.rejects(()=>resetMemberPassword(s,admin,admin,analyst.id,now,owner,deps,ok),/no linked/);await assert.rejects(()=>resetMemberPassword(s,lead,lead,m.id,now,owner,deps,ok),/administrator/);await assert.rejects(()=>resetMemberPassword(s,admin,admin,'nobody',now,owner,deps,ok),/not found/);assert.equal(calls.setPassword.length,0)});
test('another administrator cannot reset the owner password',async()=>{const {s,admin}=fixture();const other:Member={id:'adm-2',name:'Second Admin',email:'adm2@example.test',role:'Admin',teams:[],contractor:'',authUserId:crypto.randomUUID(),active:true};s.members.push(other);const {deps,calls}=fakeDeps();await assert.rejects(()=>resetMemberPassword(s,other,other,admin.id,now,owner,deps,ok),/owner/);assert.equal(calls.setPassword.length,0)});
test('nothing is changed when a reset cannot be recorded',async()=>{const {s,admin}=fixture();const m=linked(s,admin);const {deps,calls}=fakeDeps();await assert.rejects(()=>resetMemberPassword(s,admin,admin,m.id,now,owner,deps,notOk),/simultaneous/);assert.equal(calls.setPassword.length,0)});

test('deleting a member also removes their login',async()=>{const {s,admin}=fixture();const m=linked(s,admin);const {deps,calls}=fakeDeps();const r=await deleteMember(s,admin,admin,m.id,now,owner,deps,ok);assert.equal(r.loginRemoved,true);assert.equal(s.members.some(x=>x.id===m.id),false);assert.deepEqual(calls.del,[m.authUserId!])});
test('the membership is still removed if the login cannot be deleted',async()=>{const {s,admin}=fixture();const m=linked(s,admin);const {deps}=fakeDeps({async deleteLogin(){throw new Error('boom')}});const r=await deleteMember(s,admin,admin,m.id,now,owner,deps,ok);assert.equal(r.loginRemoved,false);assert.equal(s.members.some(x=>x.id===m.id),false)});
test('members with ticket records are kept and their login is untouched',async()=>{const {s,admin,analyst}=fixture();const {deps,calls}=fakeDeps();await assert.rejects(()=>deleteMember(s,admin,admin,analyst.id,now,owner,deps,ok),/ticket records/);assert.equal(s.members.some(x=>x.id===analyst.id),true);assert.equal(calls.del.length,0)});
test('delete is refused for yourself, the owner and non-admins',async()=>{const {s,admin,lead}=fixture();const m=linked(s,admin);const {deps,calls}=fakeDeps();await assert.rejects(()=>deleteMember(s,admin,admin,admin.id,now,owner,deps,ok));await assert.rejects(()=>deleteMember(s,lead,lead,m.id,now,owner,deps,ok),/administrator/);assert.equal(calls.del.length,0);assert.equal(s.members.some(x=>x.id===m.id),true)});
test('no login is deleted when the deletion cannot be saved',async()=>{const {s,admin}=fixture();const m=linked(s,admin);const {deps,calls}=fakeDeps();await assert.rejects(()=>deleteMember(s,admin,admin,m.id,now,owner,deps,notOk),/simultaneous/);assert.equal(calls.del.length,0)});
