export const statuses = ['Detected','Team assigned','Analyst assigned','Investigating','Confirmed','Notice prepared','Acknowledged','Repair in progress','Awaiting verification','Verified closed','Reopened','On hold','Rejected','Duplicate'] as const;
export type Status = typeof statuses[number];
export type Role = 'Admin'|'Team lead'|'Analyst'|'Reviewer'|'Contractor'|'Auditor';
export const colors:Record<string,string> = {'Detected':'#54667e','Team assigned':'#365cbf','Analyst assigned':'#584bc2','Investigating':'#8055bd','Confirmed':'#a8640b','Notice prepared':'#a14805','Acknowledged':'#086e99','Repair in progress':'#006d83','Awaiting verification':'#267764','Verified closed':'#167342','Reopened':'#c32643','On hold':'#68656f','Rejected':'#57606b','Duplicate':'#57606b'};
export type Member={id:string,name:string,email:string,role:Role,team:string,contractor:string;active?:boolean;authUserId?:string;demo?:boolean};
export type Ticket={id:string,title:string,road:string,lat:number,lng:number,accuracy:number,severity:string,status:Status,team:string,analyst:string,contractor:string,warranty:string,source:string,confidence:number,created:string,updated:string,due:string,reopened:number,observations:number,note:string,history:{at:string,actor:string,action:string,note:string;visibility?:'internal'|'shared'}[],verification?:string;lane?:string;contractId?:string;duplicateOf?:string;holdFrom?:Status;completedAt?:string;completedBy?:string;closedAt?:string;closedBy?:string;evidence?:Evidence[]};
export type State={tickets:Ticket[],members:Member[],teams:string[],contracts:{id:string,contractor:string,road:string,scope:string,start:string,end:string,poc:string,email:string}[],notifications:{id:string,recipient:string,ticket:string,text:string,at:string}[],events:{at:string,actor:string,action:string}[]};
export function seed(owner:string,email:string):State{
const roads=['King Street East','Hespeler Road','Dundas Street','Water Street','Bishop Street','Franklin Boulevard','Coronation Boulevard','Concession Street','Eagle Street','Dundas Street','King Street East','Water Street'];
const stages:Status[]=['Detected','Analyst assigned','Investigating','Confirmed','Notice prepared','Repair in progress','Awaiting verification','Verified closed','Reopened','On hold','Team assigned','Acknowledged'];
const now=new Date();
return {teams:['Central roads','East roads'],members:[{id:owner,name:'Workspace owner',email,role:'Admin',team:'Central roads',contractor:'',active:true,authUserId:owner},{id:'demo-lead',name:'Jordan Lee',email:'jordan@example.invalid',role:'Team lead',team:'Central roads',contractor:''},{id:'demo-analyst',name:'Avery Chen',email:'avery@example.invalid',role:'Analyst',team:'Central roads',contractor:''},{id:'demo-analyst-2',name:'Morgan Patel',email:'morgan@example.invalid',role:'Analyst',team:'East roads',contractor:''},{id:'demo-contractor',name:'Casey Brooks',email:'casey@example.invalid',role:'Contractor',team:'',contractor:'Northline Civil (demo)'},{id:'demo-reviewer',name:'Sam Rivera',email:'sam@example.invalid',role:'Reviewer',team:'Central roads',contractor:'',demo:true},{id:'demo-auditor',name:'Taylor Martin',email:'taylor@example.invalid',role:'Auditor',team:'',contractor:''}],contracts:[{id:'CT-DEMO-104',contractor:'Northline Civil (demo)',road:'King Street East',scope:'Eastbound surface course, chainage 0+000 to 0+750',start:'2025-11-01',end:'2027-11-01',poc:'Casey Brooks',email:'casey@example.invalid'},{id:'CT-DEMO-205',contractor:'Cedar Infrastructure (demo)',road:'Hespeler Road',scope:'Southbound patch zone, chainage 2+100 to 2+350',start:'2024-06-01',end:'2026-06-01',poc:'Jamie Reid',email:'jamie@example.invalid'}],notifications:[],events:[],tickets:roads.map((road,i)=>{const created=new Date(now.getTime()-(i+1)*86400000).toISOString();return {lane:'Lane 1',evidence:[],id:`PL-DEMO-2026-${String(1041+i).padStart(6,'0')}`,title:i===9?'Surface cracking':'Pothole in travel lane',road,lat:43.3605+i*0.005,lng:-80.314-i*0.002,accuracy:3.5+(i%3),severity:i%4===0?'Urgent':i%3===0?'Low':'Standard',status:stages[i],team:i%3===1?'East roads':'Central roads',analyst:i===0||i===10?'':i%3===1?'demo-analyst-2':'demo-analyst',contractor:i%3===1?'':'Northline Civil (demo)',warranty:i%3===1?'Needs review':'Candidate match',source:i%3===0?'Transit B-12':i%3===1?'Service V-08':'Volunteer V-21',confidence:0.94-(i%4)*.04,created,updated:created,due:new Date(now.getTime()+(i%4-1)*86400000).toISOString(),reopened:i===8?1:0,observations:2+i%5,note:'Illustrative record. Location, confidence, contractor and evidence are demonstration data.',history:[{at:created,actor:'Demo camera pipeline',action:'Detected',note:'Illustrative detection created; no live AI inference.'},{at:created,actor:'Demo operations',action:stages[i],note:'Seeded lifecycle example.'}]}})};
}
export const transitions:Record<string,string[]>={'Detected':['Team assigned','Rejected','Duplicate'],'Team assigned':['Analyst assigned','On hold'],'Analyst assigned':['Investigating','On hold'],'Investigating':['Confirmed','Rejected','Duplicate','On hold'],'Confirmed':['Notice prepared','Repair in progress','On hold'],'Notice prepared':['Acknowledged','On hold'],'Acknowledged':['Repair in progress','On hold'],'Repair in progress':['Awaiting verification','On hold'],'Awaiting verification':['Verified closed','Reopened','On hold'],'Verified closed':['Reopened'],'Reopened':['Investigating','Repair in progress','On hold'],'On hold':['Investigating'],'Rejected':[],'Duplicate':[]};

export type Evidence={id:string,name:string,mime:string,bytes:number,sha256:string,purpose:'detection'|'repair'|'verification',capturedAt:string,uploadedAt:string,uploadedBy:string,lat:number,lng:number,accuracy:number,lane:string,quality:'clear'|'unclear';visibility?:'internal'|'shared'};
export const roles:Role[]=['Admin','Team lead','Analyst','Reviewer','Contractor','Auditor'];
export const isActive=(m:Member)=>m.active!==false;
export const closed=(t:Ticket)=>['Verified closed','Rejected','Duplicate'].includes(t.status);
export function canSee(t:Ticket,m:Member){if(!isActive(m))return false;return m.role==='Admin'||m.role==='Auditor'||(['Team lead','Reviewer'].includes(m.role)&&t.team===m.team)||(m.role==='Analyst'&&t.analyst===m.id)||(m.role==='Contractor'&&!!m.contractor&&t.contractor===m.contractor&&['Notice prepared','Acknowledged','Repair in progress','Awaiting verification','Verified closed','Reopened','On hold'].includes(t.status));}
export function nextStages(t:Ticket):string[]{return t.status==='On hold'?[t.holdFrom||'Investigating']:(transitions[t.status]||[]);}
export function permitted(m:Member,t:Ticket,next:string){if(!canSee(t,m)||m.role==='Auditor'||!nextStages(t).includes(next))return false;if(m.role==='Contractor')return t.status!=='On hold'&&['Acknowledged','Repair in progress','Awaiting verification'].includes(next);if(next==='Verified closed')return ['Admin','Reviewer'].includes(m.role);if(m.role==='Reviewer')return ['Verified closed','Reopened','On hold'].includes(next)||(t.status==='On hold'&&next===t.holdFrom);return true;}
export function distanceMeters(a:{lat:number,lng:number},b:{lat:number,lng:number}){const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r;const h=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
export function eligibleVerification(t:Ticket,e:Evidence){return e.purpose==='verification'&&e.quality==='clear'&&e.accuracy<=10&&!!t.completedAt&&e.capturedAt>=t.completedAt&&e.lane===t.lane&&distanceMeters(t,e)<=Math.max(10,Math.min(25,t.accuracy+e.accuracy));}
export function normalizeState(s:State){for(const m of s.members){m.active??=true;m.demo??=m.id.startsWith('demo-');}for(const t of s.tickets){t.evidence??=[];t.lane??='Lane 1';}return s;}
